baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "ananke"

[markup.goldmark.renderer]
  unsafe = true


[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1


[[menu.main]]
  identifier = "about"
  name = "About Me!"
  url = "/about/"
  weight = 2 


[[menu.main]]
  identifier = "articles"
  name = "My Articles!"
  url = "/articles/"
  weight = 3 


[params.ananke]
  show_recent_posts = false # do not show recent posts on the homepage